export const ITEM_CATEGORIES: string[] = [
  "Electronics",
  "Photo & Video",
  "Books",
  "Gaming",
  "Software",
  "Sports",
  "Music",
  "Furniture",
  "Fashion",
  "Home & Garden",
  "Art",
  "Education",
  "Toys & Hobbies",
  "Automotive",
  "Health & Beauty",
  "Collectibles",
  "Services",
  "Other",
]
